name: WebHook on creation

on:
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "checkout"
      uses: actions/checkout@v3
    - name: "webhook"
      run: |
        echo "webhooooook"